In [2]:
import open3d as o3d
import numpy as np
import matplotlib.pyplot as plt
import copy
import  sys

INFO - 2023-03-25 20:03:15,102 - utils - Note: NumExpr detected 20 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO - 2023-03-25 20:03:15,103 - utils - NumExpr defaulting to 8 threads.


In [2]:
sys.path.append('..')

In [3]:
pcd = o3d.io.read_point_cloud("/home/lacie/Github/PhenomenalApp/test/corn_cropped_2.ply")
# o3d.visualization.draw_geometries([pcd])

In [4]:
# downpcd = pcd.voxel_down_sample(voxel_size = 0.005)
o3d.visualization.draw_geometries([pcd])

In [14]:
aabb = pcd.get_axis_aligned_bounding_box()
aabb.color = (1, 0, 0)
obb = pcd.get_oriented_bounding_box()
obb.color = (0, 1, 0)
o3d.visualization.draw_geometries([pcd, aabb, obb])

In [15]:
box = aabb.get_box_points()
print(np.asarray(box))

[[-0.34760001 -0.0468     -0.87169999]
 [ 0.30860001 -0.0468     -0.87169999]
 [-0.34760001  0.74870002 -0.87169999]
 [-0.34760001 -0.0468     -0.38710001]
 [ 0.30860001  0.74870002 -0.38710001]
 [-0.34760001  0.74870002 -0.38710001]
 [ 0.30860001 -0.0468     -0.38710001]
 [ 0.30860001  0.74870002 -0.87169999]]


In [5]:
def display_inlier_outlier(cloud, ind):
    inlier_cloud = cloud.select_by_index(ind)
    outlier_cloud = cloud.select_by_index(ind, invert=True)

    print("Showing outliers (red) and inliers (gray): ")
    outlier_cloud.paint_uniform_color([1, 0, 0])
    inlier_cloud.paint_uniform_color([0.8, 0.8, 0.8])
    o3d.visualization.draw_geometries([inlier_cloud, outlier_cloud])

In [6]:
cl, ind = pcd.remove_radius_outlier(nb_points=16, radius=0.05)
display_inlier_outlier(pcd, ind)

Showing outliers (red) and inliers (gray): 


In [7]:
print("Statistical oulier removal")
cl, ind = pcd.remove_statistical_outlier(nb_neighbors=20,
                                                    std_ratio=1.0)
display_inlier_outlier(pcd, ind)

Statistical oulier removal
Showing outliers (red) and inliers (gray): 


In [18]:
inlier_cloud = pcd.select_by_index(ind)

In [19]:
o3d.io.write_point_cloud("corn_removed.ply", inlier_cloud)

True

In [23]:
pcd_new = o3d.io.read_point_cloud("corn_removed.pcd")
o3d.visualization.draw_geometries([pcd_new])

In [17]:
mesh = pcd_new

In [18]:
o3d.io.write_triangle_mesh("mesh.ply", pcd_new.TriangleMesh)

TypeError: write_triangle_mesh(): incompatible function arguments. The following argument types are supported:
    1. (filename: str, mesh: open3d.cpu.pybind.geometry.TriangleMesh, write_ascii: bool = False, compressed: bool = False, write_vertex_normals: bool = True, write_vertex_colors: bool = True, write_triangle_uvs: bool = True, print_progress: bool = False) -> bool

Invoked with: 'mesh.ply', Type.TriangleMesh